import type { Experience } from "../types"

export const mockExperiences: Experience[] = [
    {
        id: "exp1",
        title: "Hike the Lost Coast",
        description: "Remote trail through California wilderness.",
        imageUrl: "https://picsum.photos/200",
        latitude: 40.12,
        longitude: -124.35,
        createdBy: "user1",
        keywords: [{ id: "k1", label: "hiking" }],
        ratingAverage: 4.7,
    },
    {
        id: "exp2",
        title: "Surf Santa Cruz",
        description: "Beginner-friendly surf experience with lessons.",
        imageUrl: "https://picsum.photos/200",
        latitude: 36.96,
        longitude: -122.02,
        createdBy: "user2",
        keywords: [{ id: "k2", label: "surfing" }],
        ratingAverage: 4.3,
    },
    {
        id: "exp3",
        title: "Wine Tour in Napa",
        description: "Visit 3 boutique wineries with a local guide.",
        imageUrl: "https://picsum.photos/200",
        latitude: 38.29,
        longitude: -122.28,
        createdBy: "user3",
        keywords: [{ id: "k3", label: "wine tasting" }],
        ratingAverage: 4.9,
    },
    {
        id: "exp4",
        title: "San Francisco Street Art Walk",
        description: "Explore iconic murals and local graffiti culture.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.77,
        longitude: -122.42,
        createdBy: "user4",
        keywords: [{ id: "k4", label: "art" }],
        ratingAverage: 4.2,
    },
    {
        id: "exp5",
        title: "Kayak the Sausalito Bay",
        description: "Paddle through scenic waters with harbor seals.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.86,
        longitude: -122.49,
        createdBy: "user5",
        keywords: [{ id: "k5", label: "kayaking" }],
        ratingAverage: 4.5,
    },
    {
        id: "exp6",
        title: "Golden Gate Sunrise Photo Tour",
        description: "Capture the perfect golden hour over SF’s skyline.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.82,
        longitude: -122.48,
        createdBy: "user6",
        keywords: [{ id: "k6", label: "photography" }],
        ratingAverage: 4.8,
    },
    {
        id: "exp7",
        title: "Oakland Jazz Night",
        description: "Experience live jazz in historic downtown venues.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.8,
        longitude: -122.27,
        createdBy: "user7",
        keywords: [{ id: "k7", label: "music" }],
        ratingAverage: 4.1,
    },
    {
        id: "exp8",
        title: "Berkeley Botanical Garden Walk",
        description: "Stroll through unique native and exotic plant zones.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.87,
        longitude: -122.26,
        createdBy: "user8",
        keywords: [{ id: "k8", label: "nature" }],
        ratingAverage: 4.6,
    },
    {
        id: "exp9",
        title: "Alcatraz Island Night Tour",
        description: "Haunting evening visit to the historic prison.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.83,
        longitude: -122.42,
        createdBy: "user9",
        keywords: [{ id: "k9", label: "history" }],
        ratingAverage: 4.4,
    },
    {
        id: "exp10",
        title: "Ferry Building Food Crawl",
        description: "Taste your way through San Francisco’s top vendors.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.79,
        longitude: -122.39,
        createdBy: "user10",
        keywords: [{ id: "k10", label: "food" }],
        ratingAverage: 4.9,
    },
    {
        id: "exp11",
        title: "Yosemite Weekend Camping",
        description: "2-night guided experience in Yosemite Valley.",
        imageUrl: "https://picsum.photos/200",
        latitude: 37.75,
        longitude: -119.59,
        createdBy: "user11",
        keywords: [{ id: "k11", label: "camping" }],
        ratingAverage: 4.8,
    },
    {
        id: "exp12",
        title: "Lake Tahoe Snowshoe Hike",
        description: "Winter hiking experience in fresh powder.",
        imageUrl: "https://picsum.photos/200",
        latitude: 39.17,
        longitude: -120.13,
        createdBy: "user12",
        keywords: [{ id: "k12", label: "snow" }],
        ratingAverage: 4.5,
    },
    {
        id: "exp13",
        title: "Santa Monica Pier Sunset Ride",
        description: "Bike along the beach during golden hour.",
        imageUrl: "https://picsum.photos/200",
        latitude: 34.01,
        longitude: -118.49,
        createdBy: "user13",
        keywords: [{ id: "k13", label: "cycling" }],
        ratingAverage: 4.6,
    },
    {
        id: "exp14",
        title: "Joshua Tree Stargazing",
        description: "Learn constellations in a dark sky park.",
        imageUrl: "https://picsum.photos/200",
        latitude: 33.87,
        longitude: -115.9,
        createdBy: "user14",
        keywords: [{ id: "k14", label: "stargazing" }],
        ratingAverage: 4.9,
    },
    {
        id: "exp15",
        title: "Big Sur Cliffside Drive",
        description: "Self-guided scenic drive with photo stops.",
        imageUrl: "https://picsum.photos/200",
        latitude: 36.27,
        longitude: -121.81,
        createdBy: "user15",
        keywords: [{ id: "k15", label: "scenic drive" }],
        ratingAverage: 4.7,
    },
]
